apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: erp-hpa
  labels:
    app: erp-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
