apiVersion: v1
kind: Secret
metadata:
  name: digitrans-secrets
  labels:
    app: digitrans-cm
type: Opaque
stringData:
  DB_USERNAME: "admin"
  DB_PASSWORD: "your-db-password"
  AZURE_AD_CLIENT_ID: "your-azure-ad-client-id"
  AZURE_AD_CLIENT_SECRET: "your-azure-ad-client-secret"
