apiVersion: v1
kind: Secret
metadata:
  name: digitrans-secrets
  labels:
    app: digitrans-cm
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  AZURE_AD_CLIENT_ID: "your-client-id"
  AZURE_AD_CLIENT_SECRET: "your-client-secret"
